# Copyright: Ankitects Pty Ltd and contributors
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

"""MCAT starter content: tagged knowledge cards and exam-style performance
questions.

Tags follow ``mcat::<section>::<topic>`` so the Rust engine can map every card
onto the embedded taxonomy for coverage and scoring. Knowledge items feed the
*memory* model; performance items (rendered with the ``MCATPerf`` notetype)
feed the *performance* model. Where a performance item probes the same idea as
a knowledge item, it is a paraphrase, which is what the transfer-gap metric
measures (recall vs. application).
"""

# (tag, front, back)
KNOWLEDGE: list[tuple[str, str, str]] = [
    # --- Chem/Phys ---
    ("mcat::chemphys::thermodynamics",
     "State the first law of thermodynamics.",
     "\u0394U = q + w; internal energy change equals heat added plus work done on the system."),
    ("mcat::chemphys::thermodynamics",
     "What is the sign of \u0394G for a spontaneous process?",
     "Negative (\u0394G < 0)."),
    ("mcat::chemphys::kinetics",
     "How does a catalyst affect a reaction?",
     "Lowers activation energy, increasing rate; does not change \u0394G or equilibrium."),
    ("mcat::chemphys::kinetics",
     "Define the rate-determining step.",
     "The slowest elementary step; it limits the overall reaction rate."),
    ("mcat::chemphys::acids_bases",
     "Define a Bronsted-Lowry acid.",
     "A proton (H+) donor."),
    ("mcat::chemphys::acids_bases",
     "What is the pH at the equivalence point of a strong acid + strong base titration?",
     "7 (neutral)."),
    ("mcat::chemphys::atomic_structure",
     "State Hund's rule.",
     "Electrons fill degenerate orbitals singly, with parallel spins, before pairing."),
    ("mcat::chemphys::electrochemistry",
     "In a galvanic cell, oxidation occurs at which electrode?",
     "The anode."),
    ("mcat::chemphys::electrochemistry",
     "What does a positive cell potential (E\u00b0cell) indicate?",
     "A spontaneous redox reaction (\u0394G < 0)."),
    ("mcat::chemphys::fluids",
     "State Bernoulli's principle qualitatively.",
     "Faster-moving fluid exerts lower pressure; total mechanical energy per volume is conserved."),
    # --- Bio/Biochem ---
    ("mcat::biobiochem::amino_acids",
     "Which amino acid is achiral?",
     "Glycine (its side chain is a hydrogen)."),
    ("mcat::biobiochem::amino_acids",
     "Name the two acidic (negatively charged) amino acids.",
     "Aspartate and glutamate."),
    ("mcat::biobiochem::protein_structure",
     "What bonds stabilize a protein's secondary structure?",
     "Hydrogen bonds between backbone amide and carbonyl groups."),
    ("mcat::biobiochem::protein_structure",
     "What covalent bond stabilizes tertiary/quaternary structure between cysteines?",
     "Disulfide bonds."),
    ("mcat::biobiochem::enzymes",
     "What does a competitive inhibitor do to Km and Vmax?",
     "Increases apparent Km; Vmax unchanged."),
    ("mcat::biobiochem::enzymes",
     "What does a noncompetitive inhibitor do to Km and Vmax?",
     "Km unchanged; Vmax decreased."),
    ("mcat::biobiochem::metabolism",
     "Where does the citric acid (Krebs) cycle occur?",
     "The mitochondrial matrix."),
    ("mcat::biobiochem::metabolism",
     "What is the net ATP yield from one glucose via aerobic respiration (typical estimate)?",
     "About 30-32 ATP."),
    ("mcat::biobiochem::glycolysis",
     "What is the net ATP and NADH yield of glycolysis per glucose?",
     "Net 2 ATP and 2 NADH."),
    ("mcat::biobiochem::glycolysis",
     "What is the committed (rate-limiting) step of glycolysis?",
     "Phosphofructokinase-1 (PFK-1) converting F6P to F1,6BP."),
    ("mcat::biobiochem::molecular_genetics",
     "In which direction does DNA polymerase synthesize?",
     "5' to 3'."),
    ("mcat::biobiochem::membranes",
     "What kind of transport moves solutes against their gradient using ATP?",
     "Primary active transport."),
    # --- Psych/Soc ---
    ("mcat::psychsoc::learning_memory",
     "Distinguish classical from operant conditioning.",
     "Classical: association between stimuli. Operant: behavior shaped by consequences (reinforcement/punishment)."),
    ("mcat::psychsoc::learning_memory",
     "What is the spacing effect?",
     "Distributed practice over time yields better retention than massed practice (cramming)."),
    ("mcat::psychsoc::sensation_perception",
     "Define the absolute threshold.",
     "The minimum stimulus intensity detectable 50% of the time."),
    ("mcat::psychsoc::sensation_perception",
     "State Weber's law.",
     "The just-noticeable difference is a constant proportion of the original stimulus."),
    ("mcat::psychsoc::cognition",
     "What is functional fixedness?",
     "A cognitive bias limiting an object to its traditional use."),
    ("mcat::psychsoc::social_psychology",
     "Define the fundamental attribution error.",
     "Overattributing others' behavior to disposition and underweighting situation."),
    ("mcat::psychsoc::social_psychology",
     "What is the mere-exposure effect?",
     "Repeated exposure to a stimulus increases liking for it."),
    ("mcat::psychsoc::identity",
     "Distinguish an achieved from an ascribed status.",
     "Achieved: earned through effort/choice. Ascribed: assigned at birth or involuntarily."),
    ("mcat::psychsoc::demographics",
     "Define demographic transition.",
     "Shift from high birth/death rates to low birth/death rates as a society industrializes."),
    # --- CARS (skills; few, since flashcards suit CARS poorly) ---
    ("mcat::cars::main_idea",
     "In a CARS passage, where is the main idea usually reinforced?",
     "The introduction and conclusion; watch for the author's thesis and evaluative language."),
    ("mcat::cars::inference",
     "What makes a valid CARS inference?",
     "It must be fully supported by the passage without adding outside assumptions."),
]

# (tag, question, answer) rendered with the MCATPerf notetype.
# ``_paraphrase`` variants intentionally probe the same idea as a KNOWLEDGE
# card to expose recall-vs-application transfer gaps.
PERFORMANCE: list[tuple[str, str, str]] = [
    ("mcat::chemphys::thermodynamics",
     "A reaction has \u0394H > 0 and \u0394S > 0. At what temperatures is it spontaneous?",
     "At high temperature (T\u0394S outweighs \u0394H, making \u0394G < 0)."),
    ("mcat::chemphys::thermodynamics",
     "A cell holds \u0394G constant while raising temperature and \u0394S is negative. What happens to spontaneity?",
     "It becomes less spontaneous (\u0394G = \u0394H - T\u0394S rises)."),
    ("mcat::chemphys::thermodynamics",
     "If a process releases heat and increases order, classify \u0394H and \u0394S.",
     "\u0394H < 0 (exothermic), \u0394S < 0 (order increases)."),
    ("mcat::chemphys::kinetics",
     "Adding a catalyst doubles the rate. What happens to Keq?",
     "Nothing; Keq is unchanged."),
    ("mcat::chemphys::kinetics",
     "For A + B -> C, doubling [A] quadruples rate. What is the order in A?",
     "Second order in A."),
    ("mcat::chemphys::kinetics",
     "A multi-step mechanism speeds up when the slow step is bypassed. Why?",
     "The rate-determining (slowest) step controls overall rate."),
    ("mcat::chemphys::acids_bases",
     "What is the pH of 0.01 M HCl?",
     "2 (strong acid fully dissociates; pH = -log[0.01])."),
    ("mcat::chemphys::acids_bases",
     "Titrating a weak acid with strong base: is the equivalence-point pH above or below 7?",
     "Above 7 (basic conjugate base remains)."),
    ("mcat::chemphys::acids_bases",
     "Identify the conjugate base of H2PO4-.",
     "HPO4^2-."),
    ("mcat::chemphys::atomic_structure",
     "How many unpaired electrons does nitrogen (2p^3) have?",
     "Three (Hund's rule: singly filled 2p orbitals)."),
    ("mcat::chemphys::atomic_structure",
     "Which has a larger radius, Na or Na+?",
     "Na (the cation is smaller)."),
    ("mcat::chemphys::electrochemistry",
     "In electrolysis, reduction occurs at which electrode?",
     "The cathode."),
    ("mcat::chemphys::electrochemistry",
     "E\u00b0cell is negative. Is the reaction spontaneous as written?",
     "No; it is nonspontaneous (\u0394G > 0)."),
    ("mcat::chemphys::electrochemistry",
     "In a galvanic cell, electrons flow from which electrode to which?",
     "From anode to cathode."),
    ("mcat::chemphys::fluids",
     "Fluid speeds up through a constriction. What happens to its pressure?",
     "It decreases (Bernoulli)."),
    ("mcat::chemphys::fluids",
     "A pipe narrows to half its area. What happens to flow velocity?",
     "It doubles (continuity: A1v1 = A2v2)."),
    ("mcat::chemphys::stoichiometry",
     "How many moles of O2 react with 2 mol H2 to form water?",
     "1 mol O2 (2 H2 + O2 -> 2 H2O)."),
    ("mcat::chemphys::stoichiometry",
     "Limiting reagent: 3 mol H2, 1 mol N2 for NH3 synthesis. Which limits?",
     "H2 (needs 3 mol H2 per N2; exactly consumed, N2 is in slight excess if <3)."),
    ("mcat::chemphys::thermochemistry",
     "Bond breaking is endothermic or exothermic?",
     "Endothermic (absorbs energy)."),
    ("mcat::chemphys::thermochemistry",
     "Using Hess's law, if step 1 = -100 kJ and step 2 = +40 kJ, net \u0394H?",
     "-60 kJ."),
    # --- Bio/Biochem ---
    ("mcat::biobiochem::amino_acids",
     "At physiological pH, what is the charge on glutamate's side chain?",
     "Negative (carboxylate, deprotonated)."),
    ("mcat::biobiochem::amino_acids",
     "Which amino acid disrupts alpha-helices due to its ring?",
     "Proline."),
    ("mcat::biobiochem::amino_acids",
     "A peptide has no stereocenter at one residue. Which amino acid is it?",
     "Glycine."),
    ("mcat::biobiochem::protein_structure",
     "Reducing agent breaks which protein bond?",
     "Disulfide bonds."),
    ("mcat::biobiochem::protein_structure",
     "Beta-sheets are stabilized by what interaction?",
     "Backbone hydrogen bonds."),
    ("mcat::biobiochem::protein_structure",
     "Denaturation by heat primarily disrupts which level of structure first?",
     "Tertiary (and quaternary); primary sequence is retained."),
    ("mcat::biobiochem::enzymes",
     "A drug raises apparent Km but leaves Vmax unchanged. Inhibitor type?",
     "Competitive."),
    ("mcat::biobiochem::enzymes",
     "An inhibitor lowers Vmax but does not change Km. Type?",
     "Noncompetitive."),
    ("mcat::biobiochem::enzymes",
     "Increasing substrate reverses inhibition. Which inhibitor type?",
     "Competitive."),
    ("mcat::biobiochem::enzymes",
     "Enzyme activity peaks then falls with rising temperature. Why the fall?",
     "Denaturation above the optimum temperature."),
    ("mcat::biobiochem::metabolism",
     "Which process occurs in the mitochondrial matrix: glycolysis or the Krebs cycle?",
     "The Krebs cycle."),
    ("mcat::biobiochem::metabolism",
     "Cyanide blocks complex IV. What happens to ATP synthesis?",
     "It halts (electron transport chain stops, no proton gradient)."),
    ("mcat::biobiochem::metabolism",
     "Under anaerobic conditions, what regenerates NAD+ in humans?",
     "Lactate fermentation."),
    ("mcat::biobiochem::glycolysis",
     "Net ATP from glycolysis if 4 are made and 2 invested?",
     "Net 2 ATP."),
    ("mcat::biobiochem::glycolysis",
     "Which enzyme is the main control point of glycolysis?",
     "PFK-1."),
    ("mcat::biobiochem::glycolysis",
     "High ATP inhibits PFK-1. What is this regulation called?",
     "Allosteric (feedback) inhibition."),
    ("mcat::biobiochem::cell_biology",
     "Which organelle is the site of aerobic ATP production?",
     "The mitochondrion."),
    ("mcat::biobiochem::cell_biology",
     "Ribosomes on the rough ER synthesize which proteins?",
     "Secretory and membrane-bound proteins."),
    ("mcat::biobiochem::molecular_genetics",
     "A lagging strand is made in fragments. What are they called?",
     "Okazaki fragments."),
    ("mcat::biobiochem::molecular_genetics",
     "DNA polymerase can only add nucleotides to which end?",
     "The 3' end."),
    ("mcat::biobiochem::membranes",
     "Na+/K+ ATPase pumps ions against gradients. Transport class?",
     "Primary active transport."),
    ("mcat::biobiochem::membranes",
     "Glucose uptake coupled to the Na+ gradient is what kind of transport?",
     "Secondary active transport (symport)."),
    # --- Psych/Soc ---
    ("mcat::psychsoc::learning_memory",
     "A dog salivates to a bell after pairing with food. Conditioning type?",
     "Classical conditioning."),
    ("mcat::psychsoc::learning_memory",
     "A rat presses a lever more after receiving food. Conditioning type?",
     "Operant conditioning (positive reinforcement)."),
    ("mcat::psychsoc::learning_memory",
     "Studying in short sessions across a week beats cramming. Which effect?",
     "The spacing effect."),
    ("mcat::psychsoc::learning_memory",
     "Removing a chore when grades improve increases studying. Reinforcement type?",
     "Negative reinforcement."),
    ("mcat::psychsoc::sensation_perception",
     "The dimmest light detectable half the time defines what?",
     "The absolute threshold."),
    ("mcat::psychsoc::sensation_perception",
     "You need a bigger change to notice loud vs. soft sounds. Which law?",
     "Weber's law."),
    ("mcat::psychsoc::sensation_perception",
     "Sensory receptors stop responding to a constant smell. This is?",
     "Sensory adaptation."),
    ("mcat::psychsoc::cognition",
     "Someone can't use a coin as a screwdriver. Which bias?",
     "Functional fixedness."),
    ("mcat::psychsoc::cognition",
     "Judging probability by how easily examples come to mind is which heuristic?",
     "The availability heuristic."),
    ("mcat::psychsoc::motivation_emotion",
     "The Yerkes-Dodson law relates performance to what?",
     "Arousal (best at moderate arousal)."),
    ("mcat::psychsoc::motivation_emotion",
     "James-Lange theory says emotion follows what?",
     "Physiological arousal (we feel afraid because we tremble)."),
    ("mcat::psychsoc::social_psychology",
     "Blaming a late coworker's character, not traffic, illustrates what?",
     "The fundamental attribution error."),
    ("mcat::psychsoc::social_psychology",
     "Liking a song more after hearing it repeatedly is which effect?",
     "The mere-exposure effect."),
    ("mcat::psychsoc::social_psychology",
     "Individuals exert less effort in a group. Name the phenomenon.",
     "Social loafing."),
    ("mcat::psychsoc::identity",
     "Being born into royalty is which kind of status?",
     "Ascribed status."),
    ("mcat::psychsoc::demographics",
     "Falling birth and death rates with industrialization describe what?",
     "The demographic transition."),
    ("mcat::psychsoc::demographics",
     "A population's age-sex breakdown is displayed with what tool?",
     "A population pyramid."),
    # --- CARS ---
    ("mcat::cars::inference",
     "A choice adds a fact not stated in the passage. Is it a valid inference?",
     "No; valid inferences use only passage support."),
    ("mcat::cars::tone_argument",
     "The author uses 'regrettably' and 'flawed'. What is the tone?",
     "Critical/negative."),
]
